.PHONY: all clean test
APP:=sample
SRC_DIR:=.
SRCS:=ics-core.c
TESTS:=sample.c

CFLAGS:=-I$(SRC_DIR)/include $(shell pkg-config --cflags libpjproject)
LIBS:=$(shell pkg-config --libs libpjproject)

all: $(APP)

$(APP): $(SRCS:.c=.o) $(TESTS:.c=.o)
	gcc -o $@ $^ $(LIBS) 
$(TESTS:.c=.o): %.o: $(SRC_DIR)/test/%.c
	gcc -c -o $@ $< $(CFLAGS) 
$(SRCS:.c=.o): %.o: $(SRC_DIR)/src/%.c
	gcc -c -o $@ $< $(CFLAGS)
clean:
	rm -fr *.o $(APP)
